version: 2
build:
  image: latest
conda:
    environment: docs/docs_environment.yml
sphinx:
    builder: html
    configuration: docs/conf.py
python:
    version: 3.7
    install:
      - method: pip
        path: .
