# environment_py2.yml
# Configuration file for creating a Conda Environment with dependencies needed for Tethys Platform.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f environment_py2.yml

name: tethys

channels:
- conda-forge
- defaults

dependencies:
- python=2.7*
- azure=0.10.0
- django=1.9.12
- django-filter
- djangorestframework
- bokeh
- paste
- psycopg2
- sqlalchemy
- requests
- PasteScript
- selenium
- coverage
- docker-py<1.10
- geoalchemy2
- owslib
- pip
- pillow
- plotly=1.12*
- postgresql
- pycrypto
- uwsgi
- pip:
    - django-gravatar2
    - django-bootstrap3
    - django-model-utils
    - django-guardian
    - django-simple-captcha
    - django-termsandconditions
    - tethys_dataset_services
    - condorpy
    - TethysCluster
    - social-auth-app-django
