# docs_environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for Tethys Platform.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f docs_environment.yml

name: tethys-docs

channels:
- conda-forge
- tethysplatform
- defaults

dependencies:
- python
- pip
- tethys_dataset_services >=2.0.0
- django =3.2.*
- sphinx
- sphinx-argparse
- pbr
- pip:
    - sphinx_materialdesign_theme
    - sphinx-autobuild
    - sphinx_autodoc_typehints
